world_frame: world
robot_base_frame: Link_0
translation:
  x: -0.26509773999452924
  y: -0.030194459192224476
  z: -0.14687563593843384
rotation:
  x: -0.1567326837230558
  y: 0.4854954612291465
  z: -0.026926856778017604
  w: 0.859653399552938
